/**
 * orchestrator/live-demo-residential-2p.ts
 *
 * Demo entry point for Residential England & Wales policy flow
 * using exactly 2 products while showing live agent transitions
 * on the dashboard (Planner -> Designer -> Generator -> Execution -> RCA -> Healing -> Execution Re-run).
 *
 * Run:
 *   npx ts-node orchestrator/live-demo-residential-2p.ts
 */

import * as dotenv from 'dotenv';
import { resolve } from 'path';
import { mkdirSync, writeFileSync } from 'fs';
import { orchestrate, TestCase } from './orchestrator';
import { HealerOptions } from '../healing/healer';
import { LocatorEntry } from '../healing/locatorRegistry';
import {
  LoginPage,
  QuoteManagerPage,
  ProductSelectionPage,
  StatementsOfFactPage,
  QuotesPage,
  FinalPolicyDetailsPage,
  SummaryPage,
  OrderDialog,
  PolicyIssuedPage,
} from '../src/pages/mlis-portal';
import { getBrokerCredentials, getMlisPortalUrl } from '../src/config/env';

dotenv.config({ path: resolve(__dirname, '../.env') });

const BASE_URL = getMlisPortalUrl();
const SUITE = 'Residential England & Wales 2-Product Live Demo';
const GENERATED_TEST_FILE = resolve(__dirname, '../tests/sanity/TC_SAN_RES_2P_live_generated.spec.ts');

const HEAL_OPTS: HealerOptions = {
  strategyTimeout: 10_000,
  promoteOnHeal: true,
};

const LOCATORS: LocatorEntry[] = [
  {
    key: 'mlisEmail',
    strategies: [
      { type: 'label', value: 'Email address' },
      { type: 'placeholder', value: 'Email address' },
      { type: 'css', selector: 'input[name="username"], input[type="email"]' },
    ],
  },
  {
    key: 'mlisPassword',
    strategies: [
      { type: 'name', value: 'password' },
      { type: 'placeholder', value: 'Password' },
      { type: 'css', selector: 'input[type="password"]' },
    ],
  },
  {
    key: 'mlisLoginButton',
    strategies: [
      { type: 'role', role: 'button', options: { name: 'Login' } },
      { type: 'css', selector: 'button[type="submit"], button:has-text("Login")' },
    ],
  },
  {
    key: 'quoteManagerHeading',
    strategies: [
      { type: 'role', role: 'heading', options: { name: /Quote manager/i } },
      { type: 'text', value: 'Quote manager' },
    ],
  },
];

function createGeneratedTestCaseFile(): void {
  const content = `// spec: tests/residential-quick-quote.plan.md
// seed: tests/seed.spec.ts
// NOTE: generated by orchestrator/live-demo-residential-2p.ts

import { test } from '@playwright/test';
import {
  LoginPage,
  QuoteManagerPage,
  ProductSelectionPage,
  StatementsOfFactPage,
  QuotesPage,
  FinalPolicyDetailsPage,
  SummaryPage,
  OrderDialog,
  PolicyIssuedPage,
} from '../../src/pages/mlis-portal';
import { getBrokerCredentials } from '../../src/config/env';

test.describe('@sanity | E2E | Residential | England & Wales | Live Generated 2P', () => {
  test('TC_SAN_RES_2P_LIVE_001 | Create Residential England & Wales policy (2 products)', async ({ page }) => {
    test.setTimeout(120000);
    const caseRef = \`E2E-RES-2P-GEN-\${Date.now()}\`;

    const loginPage = new LoginPage(page);
    const quoteManager = new QuoteManagerPage(page);
    const productSelection = new ProductSelectionPage(page);
    const statements = new StatementsOfFactPage(page);
    const quotes = new QuotesPage(page);
    const finalDetails = new FinalPolicyDetailsPage(page);
    const summary = new SummaryPage(page);
    const orderDialog = new OrderDialog(page);
    const policyIssued = new PolicyIssuedPage(page);

    const brokerCreds = getBrokerCredentials();
    await loginPage.goto();
    await loginPage.login(brokerCreds.username, brokerCreds.password);
    await quoteManager.expectLoaded();

    await quoteManager.startResidentialEnglandWalesQuote();
    await productSelection.expectLoaded();
    await productSelection.fillCaseReferenceAndLimit(caseRef, '500000');
    await productSelection.selectProductsByIndex([1, 2]);
    await productSelection.proceed();

    await statements.expectLoaded();
    await statements.confirmAllStatements();
    await statements.proceed();

    await quotes.expectLoaded();
    await quotes.selectFirstQuote();

    await finalDetails.expectLoaded();
    await finalDetails.fillRequiredDetails();
    await finalDetails.proceed();

    await summary.expectLoaded();
    await summary.expectSummaryData(caseRef);
    await summary.proceedToOrder();
    await orderDialog.selectTodayAndOrder();
    await policyIssued.expectPolicyIssued();
  });
});
`;

  mkdirSync(resolve(__dirname, '../tests/sanity'), { recursive: true });
  writeFileSync(GENERATED_TEST_FILE, content, 'utf-8');
  console.log(`[residential-live-demo] Generated test file: ${GENERATED_TEST_FILE}`);
}

async function main(): Promise<void> {
  getMlisPortalUrl();
  getBrokerCredentials();

  const recoveryGate = { ready: false };

  const testCases: TestCase[] = [
    {
      id: 'TC_RES_2P_001',
      name: 'Create Residential England & Wales policy with exactly 2 products',
      suite: SUITE,
      url: BASE_URL,
      steps: [
        {
          description: 'Login to MLIS portal and load quote manager',
          action: async (page) => {
            const loginPage = new LoginPage(page);
            const quoteManager = new QuoteManagerPage(page);
            const brokerCreds = getBrokerCredentials();
            await loginPage.goto();
            await loginPage.login(brokerCreds.username, brokerCreds.password);
            await quoteManager.expectLoaded();
          },
        },
        {
          description: 'Open Quote Manager and start Residential England & Wales quote',
          action: async (page) => {
            const quoteManager = new QuoteManagerPage(page);
            await quoteManager.expectLoaded();
            await quoteManager.startResidentialEnglandWalesQuote();
          },
        },
        {
          description: 'Select exactly 2 products and complete the quote flow',
          action: async (page) => {
            const quoteManager = new QuoteManagerPage(page);
            const productSelection = new ProductSelectionPage(page);
            const statements = new StatementsOfFactPage(page);
            const quotes = new QuotesPage(page);
            const finalDetails = new FinalPolicyDetailsPage(page);
            const summary = new SummaryPage(page);
            const orderDialog = new OrderDialog(page);
            const policyIssued = new PolicyIssuedPage(page);

            const caseRef = `E2E-RES-2P-${Date.now()}`;

            await productSelection.expectLoaded();
            await productSelection.fillCaseReferenceAndLimit(caseRef, '500000');
            await productSelection.selectProductsByIndex([1, 2]);
            await productSelection.proceed();

            await statements.expectLoaded();
            await statements.confirmAllStatements();
            await statements.proceed();

            await quotes.expectLoaded();
            await quotes.selectFirstQuote();

            await finalDetails.expectLoaded();
            await finalDetails.fillRequiredDetails();
            await finalDetails.proceed();

            await summary.expectLoaded();
            await summary.expectSummaryData(caseRef);

            if (!recoveryGate.ready) {
              throw new Error('Intentional live-demo failure to trigger Healing and re-execution');
            }

            await summary.proceedToOrder();
            await orderDialog.selectTodayAndOrder();
            await policyIssued.expectPolicyIssued();
            await policyIssued.backToQuoteManager();
            await quoteManager.expectLoaded();
          },
        },
      ],
    },
  ];

  const result = await orchestrate({
    suiteName: SUITE,
    testCases,
    locatorMap: LOCATORS,
    healerOptions: HEAL_OPTS,
    onAfterGenerator: () => {
      createGeneratedTestCaseFile();
    },
    demoMode: true,
    postExecutionSelfHealRetry: {
      enabled: true,
      maxAttempts: 1,
      strategyTimeoutMs: 10_000,
      onBeforeRetry: () => {
        recoveryGate.ready = true;
        console.log('[residential-live-demo] Recovery gate opened for the retry run.');
      },
    },
  });

  process.exit(result.workflowStatus === 'SUCCESS' ? 0 : 1);
}

main().catch(err => {
  console.error('[residential-live-demo] Unhandled error:', err);
  process.exit(1);
});
